2025-08-22 12:12:43 | CRITICAL | test_project | logger.py:346 | exception_handler | Uncaught exception
Traceback (most recent call last):
  File "<string>", line 5, in <module>
    import test_project
  File "/home/tylong/Code/github.com/ty10ng/python-template/test_project/src/test_project/__init__.py", line 13, in <module>
    from .core import App, main
  File "/home/tylong/Code/github.com/ty10ng/python-template/test_project/src/test_project/core.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
